version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}